### ISSUE TITLE
Non-growing season seems to be broken after last sprint

### ISSUE THREAD

**Issue by woodbri** [farmOS/farm_grazing#33] opened 2018-03-05 14:28 UTC
I then created the test non-growing season plan and used the same herd for that, but all the grazing days are zero on the rotations page for that plan regardless of changing productivity, etc. I think it might be related to the fact that the arrival and departure dates are blank.

Setting the dates to values that overlap the plan dates by over a year does not fix this. :( so it will require digging into it in more detail.

**Comment by mstenta** [comment] 2018-03-07 16:18
@woodbri and I dug into this today and discovered the cause: in non-growing plans, the recovery days per month are not saved to the database (because they are calculated automatically). Not sure what change broke this, because it was working originally (at least I think).

Started sketching out some code to fix this... will push to a new branch shortly...

**Comment by mstenta** [comment] 2018-03-07 16:51
My guess is that there is some code somewhere that WAS auto-calculating the recovery days for non-growing plans (rather than saving them to the database)... and THAT's what broke. Let's investigate that first... I think that would be a good place to handle this fix, rather than trying to save them to the database (and update in every possible case where things change elsewhere).

**Comment by mstenta** [comment] 2018-04-18 12:32
(Copying and pasting this from an email I just wrote to @woodbri ):

Normally (in a growing season plan), the user specifies what their min and max recovery days are for each month.  But in non-growing season plans, they are not given the option to enter these themselves.  The form at Paddocks > Recovery automatically fills them in, and disables the text fields (see attached screenshot).  It also does not provide a Save button, which is what would normally save those recovery days to the database.

So the recovery days are never being saved in the database for non-growing season plans.

When we discovered this, we were both a bit perplexed about what exactly changed to cause this, because obviously it was working when we first built it (at least I assume it was).

I looked through the code a bit this morning, and I think the issue lies in farm_grazing_get_grazing_days_for_plan_id() (in farm_grazing.utils.inc).

Look at this line: https://github.com/farmOS/farm_grazing/blob/7.x-1.x/farm_grazing.utils.inc#L166

That is querying the {farm_grazing_plan_recovery} database table for min and max recovery time.  That works fine in growing season plans, but not in non-growing season, because those values are not saved to the database.

I think we can solve this bug by wrapping line 166-170 in an "if this is a growing season plan" statement, and adding an "else" after it for non-growing season plans that auto-calculates the recovery days in the same way as it currently does in the Paddocks > Recovery form (that's grayed out).
![screenshot from 2018-04-18 08-32-51](https://user-images.githubusercontent.com/95381/38932050-1ade338c-42e3-11e8-9a94-be3f6332050c.png)

**Comment by woodbri** [comment] 2018-04-18 14:37
Ok, but the problem is that the grazing periods in the farm_grazing_rotations table are all set to zero. I don't understand why these are not getting set in the table correctly. I'll look through your comments and the code again. If you think you have a handle on it give your fix a try and see if it works.

**Comment by mstenta** [comment] 2018-04-18 14:57
Maybe it's more than one issue?  You're right: I wouldn't expect a bug with the recovery days to affect the grazing days, but maybe they are affected by one another... Or maybe our initial prognosis was also wrong...

**Comment by woodbri** [comment] 2018-04-18 15:00
Going back to the spreadsheet for the non growing season, these seem to be the critical equations:

- Recovery Period = Total Grazing Days Requires / # rotations
- Total Grazing Days Requires = Expected Days of Non-growth + Days Drought Reserve - Days Bulk Feeding
- Grazing Period = Recovery Period / # paddocks
- Drought Reserve Grazing Period = Days Drought Reserve / # paddocks
So Grazing Period is based on Recovery Period so it looks like your idea is probably correct.

**Comment by mstenta** [comment] 2018-06-11 18:35
Alright! I think I fixed this!

https://github.com/farmOS/farm_grazing/commit/a74c6b0ab562f78d1bac312131f4f5fc8bd5e67f

I modified the logic in `farm_grazing_get_grazing_days_for_plan_id()` so that it calculates the recovery period for non-growing season plans, rather than trying to load them from the database (where they are not saved).

Now when rotations are added/recalculated, the grazing days are not zero anymore. I've committed and pushed this fix.

@woodbri Could you give this a test on your local non-grazing plan when you have a chance to make sure it works for you? If you find any issues with it, please reopen this.

Also, I created a new task for consolidating some of the calculation logic, so that it's easy to track it down in one place in the future: https://github.com/farmOS/farm_grazing/issues/41 - For now I just copied the logic again for this fix - so we should do a thorough refactor to consolidate everything at once.

**Closed as completed by mstenta** 2018-06-11 18:35 UTC
Labels: bug
